version: "3.7"

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
    ports:
      - 9092:9092
  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - '3001:3001'
    environment:
      - API_GATEWAY_PORT=3001
      - TRANSACTION_SERVICE_URL=http://transaction-service:3002
      - KAFKA_BROKER=kafka:29092
    depends_on:
      - transaction-service
      - antifraud-service
  transaction-service:
    build:
      context: .
      dockerfile: ./transaction-service/Dockerfile
    ports:
      - '3002:3002'
    environment:
      - TRANSACTION_SERVICE_PORT=3002
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - KAFKA_BROKER=kafka:29092
      - TIME_ZONE=America/Lima
    depends_on:
      - postgres
      - kafka
  antifraud-service:
    build:
      context: .
      dockerfile: ./antifraud-service/Dockerfile
    ports:
      - '3003:3003'
    environment:
      - KAFKA_BROKER=kafka:29092
      - ANTI_FRAUD_AMOUNT_LIMIT=1000
    depends_on:
      - kafka

volumes:
  pgdata: